###
GET http://localhost:3001/api/schedules
Origin: http://localhost:3001

###
DELETE http://localhost:3001/api/schedules/f89ab822-79e8-42b4-af84-ded1304b6595
Origin: http://localhost:3001

### 
GET http://localhost:3001/api/schedules/cf2b8f59-965f-4924-87b7-e4ca4e51cf2c/test/