###
GET http://localhost:3001/api/schedules
Origin: http://localhost:3001

###
DELETE http://localhost:3001/api/schedules/c42c4bb7-dbda-41ce-bd5a-e380d116352a
Origin: http://localhost:3001

### 
GET http://localhost:3001/api/schedules/cf2b8f59-965f-4924-87b7-e4ca4e51cf2c/test/