###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "email": "user@email.com",
  "name": "Test User",
  "role": "client"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "email": "jane@email.com",
  "name": "Jane Doe",
  "role": "employee"
}

###
POST http://localhost:3001/api/users/test 
Content-Type: application/json

{
  "date": "2024-01-26", 
  "startTime": "17:00", 
  "endTime": "17:30",
  "clientId": "6ac161c5-b033-412e-8d35-06cd46dbd59a",
  "employeeId": "b8e97212-71a5-4206-a674-0781e3a39c58",
  "service": "Haircut"
}