
###
POST http://localhost:3001/api/appointments
Content-Type: application/json

{
  "date": "2024-01-24", 
  "startTime": "17:00", 
  "endTime": "17:30",
  "clientId": "80904efc-67d3-4ac4-95d3-3cd5965c5fcc",
  "employeeId": "a50b56e6-713a-4c0e-9996-439be75dc5c8"
}


