###
GET http://localhost:3001/api/appointments

###
DELETE http://localhost:3001/api/appointments/90b69c53-7d47-4fd0-966b-33ac8ba25d76



### update appointment status 
PUT http://localhost:3001/api/appointments/status/2e2b5f2a-57a6-41e4-b9e5-30de801c692f
Origin: http://localhost:3001
Content-Type: application/json

{
  "status": "checked-in"
}

###
PUT http://localhost:3001/api/appointments/2e2b5f2a-57a6-41e4-b9e5-30de801c692f
Content-Type: application/json

{
  "date": "2024-02-03",
  "start": "12:00",
  "end": "13:00",
  "service": "The Full Package",
  "clientId": "6ac161c5-b033-412e-8d35-06cd46dbd59a",
  "employeeId": "e123b115-d3a2-4c7e-a45d-f82fde101161"
}

### Should not pass validation
PUT http://localhost:3001/api/appointments/fake_id
Content-Type: application/json

{
  "date": "2024-01-29",
  "start": "",
  "end": "12:30",
  "service": "The Full Package",
  "clientId": "6ac161c5-b033-412e-8d35-06cd46dbd59a",
  "employeeId": "e123b115-d3a2-4c7e-a45d-f82fde101161"
}

### Test route
PUT http://localhost:3001/api/appointments/744409cc-8fda-472f-953f-ba0a8068d768/test
