###
GET http://localhost:3001/api/appointments

###
DELETE http://localhost:3001/api/appointments/90b69c53-7d47-4fd0-966b-33ac8ba25d76

###
PUT http://localhost:3001/api/appointments/1f3c27a2-9f8a-46e6-aa51-46ef2dc10257
Content-Type: application/json

{
  "date": "2024-01-29",
  "startTime": "12:00",
  "endTime": "12:30",
  "service": "The Full Package",
  "clientId": "6ac161c5-b033-412e-8d35-06cd46dbd59a",
  "employeeId": "e123b115-d3a2-4c7e-a45d-f82fde101161"
}

### Should not pass validation
PUT http://localhost:3001/api/appointments/fake_id
Content-Type: application/json

{
  "date": "2024-01-29",
  "startTime": "",
  "endTime": "12:30",
  "service": "The Full Package",
  "clientId": "6ac161c5-b033-412e-8d35-06cd46dbd59a",
  "employeeId": "e123b115-d3a2-4c7e-a45d-f82fde101161"
}

### Test route
PUT http://localhost:3001/api/appointments/744409cc-8fda-472f-953f-ba0a8068d768/test
