###
GET http://localhost:3001/api/appointments

###
DELETE http://localhost:3001/api/appointments/90b69c53-7d47-4fd0-966b-33ac8ba25d76

###
PUT http://localhost:3001/api/appointments/ebd6eaa6-4dc3-40f1-b396-4b85d3af38fd
Content-Type: application/json

{
  "date": "2024-01-25",
  "startTime": "17:00:00",
  "endTime": "17:30:00",
  "clientId": "96b0cfd3-8c5f-4bb7-8946-c550e1e36f99",
  "employeeId": "6383181b-e1e5-4931-a43f-090eccd9f7e7"
}
